kind: AIchorManifest
apiVersion: 0.2.2
 
builder:
  image: image
  dockerfile: ./build/ray.Dockerfile
  context: .
 
#clone: # optional
#  includeDotGit: true # optional: boolean, defaults to false
#  submodules: "true" # optional: string, defaults to “false”. Options are “false”, “true”, “recursive”.
     
spec:
  operator: kuberay
  image: image
  command: "python3 -u main.py --operator=kuberay --sleep=300 --tb-write=True"
 
  debug:
    jupyter: false

  tensorboard:
    enabled: true
 
  types:
    Head:
      resources:
        cpus: 1
        ramRatio: 2

    Workers:
      - name: cpu-workers
        count: 1
        resources:
          cpus: 1
          ramRatio: 2
          shmSizeGB: 0
 
